version: '3.3'
networks:
  mqtt_default:
    external: true
services:
  radio:
    container_name: radio
    restart: on-failure
    devices:
      - ${RTL_PATH}
    environment:
      - RTL_DEVICE=${RTL_PATH}
      - FREQ=152007500
      - DEBUG=True
    image: norcom_radio:latest
    volumes: 
      - ./local_settings.py:/app/local_settings.py
    networks:
      mqtt_default:
